// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPIfCH8x3VmNmaMiUcmYqeuIXLglGKfl0',
    appId: '1:587591497637:web:2e7f2607d3f05c5aa95a4c',
    messagingSenderId: '587591497637',
    projectId: 'expenses-45044',
    authDomain: 'expenses-45044.firebaseapp.com',
    storageBucket: 'expenses-45044.appspot.com',
    measurementId: 'G-TPK6R7N0CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9YK6Ow72AHlWq1iFhVCjkJdoYA2rZGWU',
    appId: '1:587591497637:android:3b0e23c6b74397a0a95a4c',
    messagingSenderId: '587591497637',
    projectId: 'expenses-45044',
    storageBucket: 'expenses-45044.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOL1XalYbj-SP8aPg2T1dVzccq4FJRwbM',
    appId: '1:587591497637:ios:f39909eba4b74f20a95a4c',
    messagingSenderId: '587591497637',
    projectId: 'expenses-45044',
    storageBucket: 'expenses-45044.appspot.com',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOL1XalYbj-SP8aPg2T1dVzccq4FJRwbM',
    appId: '1:587591497637:ios:2e07fd7f9860985fa95a4c',
    messagingSenderId: '587591497637',
    projectId: 'expenses-45044',
    storageBucket: 'expenses-45044.appspot.com',
    iosBundleId: 'com.example.expenses.RunnerTests',
  );
}
