/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String apple = "assets/images/apple.svg";
  static const String ar = "assets/lang/ar.json";
  static const String arrow = "assets/images/arrow.svg";
  static const String cart = "assets/images/cart.png";
  static const String country = "assets/images/country.png";
  static const String currency = "assets/images/currency.png";
  static const String currencyExchange = "assets/images/currencyExchange.png";
  static const String dollar = "assets/images/dollar.png";
  static const String en = "assets/lang/en.json";
  static const String facebook = "assets/images/facebook.svg";
  static const String forgetPassword = "assets/images/forgetPassword.png";
  static const String home = "assets/images/home.png";
  static const String icon = "assets/images/icon.png";
  static const String lang = "assets/images/lang.png";
  static const String launcherIcon = "assets/images/launcher_icon.png";
  static const String logo = "assets/images/logo.png";
  static const String marker = "assets/images/marker.png";
  static const String mobile = "assets/images/mobile.svg";
  static const String onboardingOne = "assets/images/onboardingOne.jpeg";
  static const String onboardingThree = "assets/images/onboardingThree.jpeg";
  static const String onboardingTwo = "assets/images/onboardingTwo.jpeg";
  static const String password = "assets/images/password.svg";
  static const String register = "assets/images/register.png";
  static const String twitter = "assets/images/twitter.png";
  static const String upload = "assets/images/upload.png";
}
